
services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    healthcheck:
      # test: curl http://localhost:${OLLAMA_PORT} 2>/dev/null || exit 1
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./ollama/ollama_data:/root/.ollama
    networks:
      - localbridge
    ports:
      - "${OLLAMA_PORT}:${OLLAMA_PORT}"
    env_file: .env
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - openwebui_data:/app/backend/data
    networks:
      - localbridge
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"
    env_file: .env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  openwebui_data: {}

networks:
  localbridge:
    driver: bridge
  privatenet:
    internal: true