
services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    tty: true
    restart: unless-stopped
    volumes:
      - ./ollama/ollama_data:/root/.ollama
    networks:
      - localbridge
    ports:
      - "${OLLAMA_PORT}:${OLLAMA_PORT}"
    env_file: .env
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  setup:
    image: alpine:latest
    container_name: setup
    networks:
      - localbridge
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      ollama:
        condition: service_healthy
    tty: true
    command: sh -c "apk add --no-cache docker && docker -H unix:///var/run/docker.sock exec -it ollama sh -c 'ollama pull gemma3:1b'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./open-webui/data:/app/backend/data
    networks:
      - localbridge
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"
    env_file: .env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  openwebui_data: {}

networks:
  localbridge:
    driver: bridge
  privatenet:
    internal: true